export {default as Login} from './Login';
export {default as Home} from './Home';
export {default as Header} from './Header';
export {default as FormSearch} from './FormSearch';
export {default as MainContent} from './MainContent'    
export {default as Register} from './Register'   
export {default as NotFound}  from './NotFound'
export {default as Cart}  from './Cart'
export {default as Detail}  from './Detail'
export {default as City}  from './City'
export {default as Profile}  from './Profile'